## Introduction to `NumPy`
NumPy, short for Numerical Python, is a powerful library for numerical computing in Python. It provides support for arrays, matrices, and many mathematical functions.

#### Step 1: Installation and Importing


In [4]:
!pip install numpy


[notice] A new release of pip available: 22.3.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

#### Step 2: Creating Arrays
Scenario: Imagine you need to create arrays to store data for analysis, such as a list of temperatures over a week.

In [6]:
#1D Array

temperatures = np.array([23, 25, 19, 22, 30, 28, 24])
print(temperatures)

[23 25 19 22 30 28 24]


In [19]:
#2D Array

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)


#np.shape(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
#Zeros and Ones Arrays:

zeros_array = np.zeros((3, 3))
ones_array = np.ones((2, 4))
print(zeros_array)
print(ones_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### Step 3: Array Operations
Scenario: You have two arrays representing the sales of two products over a week. You want to perform basic arithmetic operations to analyze the sales data.

In [9]:
product1_sales = np.array([10, 20, 30, 40, 50, 60, 70])
product2_sales = np.array([5, 15, 25, 35, 45, 55, 65])

# Addition
total_sales = product1_sales + product2_sales
print(total_sales)

# Subtraction
sales_diff = product1_sales - product2_sales
print(sales_diff)

# Multiplication
sales_mult = product1_sales * product2_sales
print(sales_mult)

# Division
sales_div = product1_sales / product2_sales
print(sales_div)


[ 15  35  55  75  95 115 135]
[5 5 5 5 5 5 5]
[  50  300  750 1400 2250 3300 4550]
[2.         1.33333333 1.2        1.14285714 1.11111111 1.09090909
 1.07692308]


#### Step 4: Statistical Operations
Scenario: You have collected students' scores in a test and want to calculate statistical data like mean, median, and standard deviation

In [10]:
scores = np.array([85, 90, 78, 92, 88, 76, 95, 89])

# Mean
mean_score = np.mean(scores)
print("Mean Score:", mean_score)

# Median
median_score = np.median(scores)
print("Median Score:", median_score)

# Standard Deviation
std_deviation = np.std(scores)
print("Standard Deviation:", std_deviation)


Mean Score: 86.625
Median Score: 88.5
Standard Deviation: 6.203577596838779


#### Step 5: Indexing and Slicing
Scenario: You want to extract specific data from an array, such as temperatures on the first three days of the week.

In [11]:
temperatures = np.array([23, 25, 19, 22, 30, 28, 24])

# Indexing
first_day_temp = temperatures[0]
print("Temperature on first day:", first_day_temp)

# Slicing
first_three_days_temp = temperatures[:3]
print("Temperatures on first three days:", first_three_days_temp)


Temperature on first day: 23
Temperatures on first three days: [23 25 19]


#### Step 6: Reshaping Arrays
Scenario: You have a linear array of 12 elements and want to reshape it into a 3x4 matrix for easier analysis.

In [12]:
linear_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
matrix_3x4 = linear_array.reshape((3, 4))
print(matrix_3x4)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### Step 7: Concatenation and Splitting
Scenario: You need to combine sales data from two weeks or split it into daily and weekly data.

In [13]:
#Concatenation

week1_sales = np.array([10, 20, 30, 40, 50, 60, 70])
week2_sales = np.array([15, 25, 35, 45, 55, 65, 75])

total_sales = np.concatenate((week1_sales, week2_sales))
print(total_sales)


[10 20 30 40 50 60 70 15 25 35 45 55 65 75]


In [14]:
#splitting

daily_sales = np.array([10, 20, 30, 40, 50, 60, 70, 15, 25, 35, 45, 55, 65, 75])
week1_sales, week2_sales = np.split(daily_sales, 2)
print("Week 1 Sales:", week1_sales)
print("Week 2 Sales:", week2_sales)


Week 1 Sales: [10 20 30 40 50 60 70]
Week 2 Sales: [15 25 35 45 55 65 75]


#### Step 8: Broadcasting
Scenario: You want to increase all temperatures by 2 degrees for a week.

In [15]:
temperatures = np.array([23, 25, 19, 22, 30, 28, 24])
temperatures += 2
print("Updated Temperatures:", temperatures)


Updated Temperatures: [25 27 21 24 32 30 26]


#### Step 9: Advanced Operations
Scenario: You have data for two matrices representing different datasets and want to perform matrix multiplication.

In [16]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.dot(matrix1, matrix2)
print(result)


[[19 22]
 [43 50]]


## `Important NumPy Methods`


###### `np.arange(start, stop, step)` - Returns evenly spaced values within a given interval.
###### `np.linspace(start, stop, num)` - Returns evenly spaced numbers over a specified interval.
###### `np.random.rand(d0, d1, ..., dn)` - Generates random numbers.
###### `np.sum(array)` - Sum of array elements.
###### `np.max(array)` - Maximum value of array elements.
###### `np.min(array)` - Minimum value of array elements.
###### `np.argmax(array)` - Indices of the maximum values.
###### `np.argmin(array)` - Indices of the minimum values.
###### `np.unique(array)` - Find the unique elements of an array.
###### `np.transpose(array)` - Permute the dimensions of an array.


## `Conclusion`

##### This tutorial provides a comprehensive overview of NumPy's capabilities. Practice these examples and scenarios to get a solid understanding of how NumPy can be used in various data analysis tasks. Encourage students to experiment with the code and come up with their own scenarios for a deeper understanding.