## **`Linear Algebra and Calculus`**

### Here are the topics :

#### 1. `Vectors and matrices`
#### 2. `Linear equations`
#### 3. `Eigenvalues and eigenvectors`
#### 4. `Matrix transpose and inverse`
#### 5. `Matrix multiplication and factorization`
#### 6. `Linear transformations`
#### 7. `Differentiation, integration, and gradient descent`

### 1. **Vectors and Matrices**

**Concept Explanation:**
- **Vectors:** In linear algebra, vectors are elements of a vector space, which can be represented as an array of numbers. They can represent points, directions, or other quantities.
- **Matrices:** A matrix is a rectangular array of numbers arranged in rows and columns. Matrices are used to represent linear transformations, systems of linear equations, and more.

In [2]:
import numpy as np

# Define a vector
vector = np.array([2, 3, 5]) #1D

# Define a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]) #3x3

print("Vector:")
print(vector)

print("\nMatrix:")
print(matrix)




# Explanation:

# We used numpy to define a vector and a matrix. The vector is a one-dimensional array, while the matrix is a two-dimensional array.
# This basic representation is foundational for more complex operations in linear algebra.

Vector:
[2 3 5]

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2. **Linear Equations**

**Concept Explanation:**
- Linear equations are equations of the first degree, meaning they involve only linear terms (no exponents or powers). They are often represented in matrix form as \(Ax = b\), where \(A\) is a matrix of coefficients, \(x\) is a vector of unknowns, and \(b\) is a vector of constants.

In [5]:
#Ax=b

#3x+5y=3 x2
#2x+3y=6 x3

# find the values of x and y

# Coefficient matrix A
# A = np.array([[3, 2, -1],
#               [2, -2, 4],
#               [-1, 0.5, -1]]) #3x3

A=np.array([
    [3,5],
    [2,3]
])


# # Constants vector b
# b = np.array([1, -2, 0])

b=np.array([3,6])

# # Solve for x
x = np.linalg.solve(A, b)

# print("Solution for x:")
print(x)

# Explanation:

# Here, we used numpy.linalg.solve() to solve the system of linear equations 
# 𝐴
# 𝑥
# =
# 𝑏
# Ax=b. This function finds the vector 
# 𝑥
# x that satisfies the equation.

[ 21. -12.]


### 3. **Eigenvalues and Eigenvectors**

**Concept Explanation:**
- **Eigenvalues and Eigenvectors:** For a given square matrix \(A\), if \(v\) is a non-zero vector, and \(\lambda\) is a scalar such that \(Av = \lambda v\), then \(v\) is an eigenvector of \(A\), and \(\lambda\) is its corresponding eigenvalue.

What Are Eigenvalues and Eigenvectors?

Imagine you have a piece of paper with an arrow drawn on it. Now, you can stretch, rotate, or squash the paper, and that arrow will change in some way—its direction might change, and its length might change.

Eigenvector: It's like a special arrow that, when you transform (stretch, rotate, etc.) the paper, it either stays pointing in the same direction or flips to point exactly opposite. It doesn’t twist off in some random direction. It’s like a steady arrow that holds its direction no matter how the paper is moved.

Eigenvalue: This is the amount by which the eigenvector is stretched or squashed. If the eigenvalue is 2, it means the arrow (eigenvector) gets twice as long. If it's 0.5, the arrow gets half as long. If it’s a negative number, it means the arrow flips direction and stretches or squashes by that amount.



Where Are They Useful in Machine Learning?
Eigenvalues and eigenvectors are super important in machine learning, especially when dealing with data. Here's why:

Principal Component Analysis (PCA):

What It Does: PCA is a technique used to simplify complex data by reducing the number of dimensions (like compressing a big, detailed picture into a smaller one without losing too much important information).
How It Uses Eigenvalues and Eigenvectors: It finds the eigenvectors (directions) where the data varies the most, and the eigenvalues tell you how much of the data's "story" is captured in each direction. By focusing on the directions with the biggest eigenvalues, you can simplify the data while still keeping the important parts.
Understanding Patterns:

In many machine learning algorithms, we need to find patterns or understand how data is structured. Eigenvalues and eigenvectors help us identify these patterns by highlighting the most important directions in the data.
Facial Recognition:

In facial recognition, eigenfaces (a term derived from eigenvectors) are used. The algorithm learns the important features of faces (like eyes, nose, etc.) by analyzing the data's eigenvectors and eigenvalues, helping it to recognize faces more efficiently.

In [6]:
#a.v=lambda.v

# Define a square matrix
a = np.array([[4, -2],
                   [1,  1]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(a)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

# **Explanation:**
# - We used `numpy.linalg.eig()` to calculate the eigenvalues and eigenvectors of the matrix.
# Eigenvalues are crucial in understanding the properties of matrices and linear transformations.

Eigenvalues:
[3. 2.]

Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


### 4. **Matrix Transpose and Inverse**

**Concept Explanation:**
- **Transpose:** The transpose of a matrix is obtained by swapping its rows with its columns.
- **Inverse:** The inverse of a matrix \(A\) is another matrix \(A^{-1}\) such that \(AA^{-1} = I\), where \(I\) is the identity matrix.

In [8]:
# Transpose of a matrix
matrix = np.array([[4, -2],
                   [1,  1]])

transpose_matrix = matrix.T

# Inverse of a matrix
inverse_matrix = np.linalg.inv(matrix)

print("Transpose of the matrix:")
print(transpose_matrix)

print("\nInverse of the matrix:")
print(inverse_matrix)


# **Explanation:**
# - The `.T` attribute is used to transpose the matrix, and `numpy.linalg.inv()` is used to calculate the inverse. 
# These operations are fundamental in solving systems of linear equations and in various applications like computer graphics and machine learning.

Transpose of the matrix:
[[ 4  1]
 [-2  1]]

Inverse of the matrix:
[[ 0.16666667  0.33333333]
 [-0.16666667  0.66666667]]


### 5. **Matrix Multiplication and Factorization**

**Concept Explanation:**
- **Matrix Multiplication:** The product of two matrices is obtained by multiplying rows by columns.
- **Factorization:** Matrix factorization (like LU decomposition) breaks down a matrix into simpler components.

In [12]:
%pip install scipy

   ---------------------------------------- 0.0/44.8 MB ? eta -:--:--
   ---------------------------------------- 0.5/44.8 MB 3.4 MB/s eta 0:00:14
   - -------------------------------------- 2.1/44.8 MB 5.9 MB/s eta 0:00:08
   ---- ----------------------------------- 5.0/44.8 MB 8.9 MB/s eta 0:00:05
   ------- -------------------------------- 7.9/44.8 MB 10.1 MB/s eta 0:00:04
   --------- ------------------------------ 10.5/44.8 MB 10.7 MB/s eta 0:00:04
   ----------- ---------------------------- 13.1/44.8 MB 11.1 MB/s eta 0:00:03
   -------------- ------------------------- 15.7/44.8 MB 11.4 MB/s eta 0:00:03
   ---------------- ----------------------- 18.6/44.8 MB 11.6 MB/s eta 0:00:03
   ------------------ --------------------- 21.2/44.8 MB 11.8 MB/s eta 0:00:02
   --------------------- ------------------ 23.9/44.8 MB 11.9 MB/s eta 0:00:02
   ----------------------- ---------------- 26.7/44.8 MB 12.0 MB/s eta 0:00:02
   -------------------------- ------------- 29.4/44.8 MB 12.1 MB/s e

LU Decomposition is like breaking down a complicated task into smaller, easier steps. Imagine you have a big LEGO structure. Instead of dealing with the whole thing at once, you first take it apart into smaller pieces (like walls and roofs) and then handle each piece separately. In math, LU Decomposition does something similar for matrices, which are big grids of numbers.

Here’s how it works:

L stands for "Lower triangular matrix," which is like a set of simpler building blocks (like the base of your LEGO structure).
U stands for "Upper triangular matrix," which is another set of blocks (like the roof of your LEGO structure).
So, LU Decomposition splits a complicated matrix into two simpler ones: L and U. This makes solving math problems, like finding solutions to systems of linear equations, much easier



P×A=L×U

Where:

P is the permutation matrix (rearranging rows).
A is the original matrix.
L is the lower triangular matrix.
U is the upper triangular matrix.

In [13]:
# Matrix multiplication
product = np.dot(matrix,inverse_matrix)

print("Matrix Product:")
print(product)

##LU Decomposition

from scipy.linalg import lu
P, L, U = lu(matrix)

print("\nLU Decomposition:")
print("P Matrix:\n", P)
print("L Matrix:\n", L)
print("U Matrix:\n", U)




# **Explanation:**
# - We used `numpy.dot()` for matrix multiplication and `scipy.linalg.lu()` for LU decomposition, which is a factorization of a matrix into a product of a lower triangular matrix and an upper triangular matrix.


Matrix Product:
[[1.00000000e+00 0.00000000e+00]
 [2.77555756e-17 1.00000000e+00]]

LU Decomposition:
P Matrix:
 [[1. 0.]
 [0. 1.]]
L Matrix:
 [[1.   0.  ]
 [0.25 1.  ]]
U Matrix:
 [[ 4.  -2. ]
 [ 0.   1.5]]


### 6. **Linear Transformations**

**Concept Explanation:**
- **Linear Transformations:** A linear transformation is a mapping between two vector spaces that preserves the operations of vector addition and scalar multiplication. These can be represented by matrices.

In [14]:
# Linear transformation matrix
transformation_matrix = np.array([[2, 0],
                                  [0, 3]])

##(2x2).(1x2)

# Apply transformation to a vector
transformed_vector = np.dot(transformation_matrix, vector[:2])

print("Transformed Vector:")
print(transformed_vector)

# **Explanation:**
# - The transformation matrix scales the input vector by different factors along different axes. 
# This concept is widely used in computer graphics for scaling, rotation, and other transformations.

Transformed Vector:
[4 9]


## **`Calculus`**

### 7. **Differentiation, Integration, and Gradient Descent**

**Concept Explanation:**
- **Differentiation:** It is the process of finding the derivative of a function, which gives the rate of change of the function with respect to a variable.
- **Integration:** The process of finding the integral of a function, representing the area under the curve of the function.
- **Gradient Descent:** An optimization algorithm used to minimize functions by iteratively moving in the direction of the steepest descent as defined by the negative of the gradient.

In [6]:
%pip install sympy

   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.2 MB ? eta -:--:--
   ----- ---------------------------------- 0.8/6.2 MB 1.7 MB/s eta 0:00:04
   -------- ------------------------------- 1.3/6.2 MB 2.0 MB/s eta 0:00:03
   ------------- -------------------------- 2.1/6.2 MB 2.5 MB/s eta 0:00:02
   -------------------- ------------------- 3.1/6.2 MB 3.1 MB/s eta 0:00:01
   ------------------------------ --------- 4.7/6.2 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 6.2/6.2 MB 4.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/536.2 kB ? eta -:--:--
   ---------------------------------------- 536.2/536.2 kB 5.8 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [15]:
import sympy as sp

# Define a symbol
x = sp.symbols('x')

# Define a function
f = x**3 + 2*x**2 + x + 1 #f(x)=x^3+2x^2+x+1 

# Differentiation
f_prime = sp.diff(f, x) #f'(x)=x^3+2x^2+x+1= 3x^2+4x+1 

# Integration
f_integral = sp.integrate(f, x) 

print("Function:")
sp.pprint(f)

print("\nDerivative:")
sp.pprint(f_prime)

print("\nIntegral:")
sp.pprint(f_integral)

# Gradient Descent example
def gradient_descent(f_prime, start, learning_rate, iterations):
    x_value = start
    for _ in range(iterations):
        x_value = x_value - learning_rate * f_prime.subs(x, x_value)
    return x_value

# Apply gradient descent
min_value = gradient_descent(f_prime, start=0, learning_rate=0.01, iterations=1000)
print("\nMinimum value found by Gradient Descent:", min_value)


# <!-- **Explanation:**
# - `sympy` is used for symbolic mathematics in Python. 
# We defined a function, computed its derivative and integral, 
# and then demonstrated gradient descent to find a local minimum of the function.

Function:
 3      2        
x  + 2⋅x  + x + 1

Derivative:
   2          
3⋅x  + 4⋅x + 1

Integral:
 4      3    2    
x    2⋅x    x     
── + ──── + ── + x
4     3     2     

Minimum value found by Gradient Descent: -0.333333332962430
